In [1]:
import pandas as pd  
import numpy as np   


In [82]:
df = pd.read_csv("data/dirty_cafe_sales.csv")

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB


In [84]:
df = df.replace(['UNKNOWN', 'ERROR'], pd.NA)  
df = df.dropna()  

In [85]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

In [86]:
df.head()

Transaction ID      Item  Quantity Price Per Unit Total Spent  \
0     TXN_1961373    Coffee         2            2.0         4.0   
1     TXN_4977031      Cake         4            3.0        12.0   
4     TXN_3160411    Coffee         2            2.0         4.0   
10    TXN_2548360     Salad         5            5.0        25.0   
12    TXN_7619095  Sandwich         2            4.0         8.0   

    Payment Method  Location Transaction Date  
0      Credit Card  Takeaway       2023-09-08  
1             Cash  In-store       2023-05-16  
4   Digital Wallet  In-store       2023-06-11  
10            Cash  Takeaway       2023-11-07  
12            Cash  In-store       2023-05-03

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3089 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Transaction ID    3089 non-null   object
 1   Item              3089 non-null   object
 2   Quantity          3089 non-null   int64 
 3   Price Per Unit    3089 non-null   object
 4   Total Spent       3089 non-null   object
 5   Payment Method    3089 non-null   object
 6   Location          3089 non-null   object
 7   Transaction Date  3089 non-null   object
dtypes: int64(1), object(7)
memory usage: 217.2+ KB


In [88]:
df.describe

<bound method NDFrame.describe of      Transaction ID      Item  Quantity Price Per Unit Total Spent  \
0       TXN_1961373    Coffee         2            2.0         4.0   
1       TXN_4977031      Cake         4            3.0        12.0   
4       TXN_3160411    Coffee         2            2.0         4.0   
10      TXN_2548360     Salad         5            5.0        25.0   
12      TXN_7619095  Sandwich         2            4.0         8.0   
...             ...       ...       ...            ...         ...   
9975    TXN_9668108      Cake         1            3.0         3.0   
9979    TXN_9933628  Smoothie         5            4.0        20.0   
9986    TXN_2858441  Sandwich         2            4.0         8.0   
9991    TXN_3897619  Sandwich         3            4.0        12.0   
9999    TXN_6170729  Sandwich         3            4.0        12.0   

      Payment Method  Location Transaction Date  
0        Credit Card  Takeaway       2023-09-08  
1               Cash  In-

In [89]:
df[['Quantity']]

Quantity
0            2
1            4
4            2
10           5
12           2
...        ...
9975         1
9979         5
9986         2
9991         3
9999         3

[3089 rows x 1 columns]

In [44]:
df.loc[:3]

Transaction ID    Item  Quantity Price Per Unit Total Spent Payment Method  \
0    TXN_1961373  Coffee       2.0            2.0         4.0    Credit Card   
1    TXN_4977031    Cake       4.0            3.0        12.0           Cash   

   Location Transaction Date  
0  Takeaway       2023-09-08  
1  In-store       2023-05-16

In [45]:
df.iloc[2, 1]

'Coffee'

In [46]:
df[df['Quantity'] > 3]

Transaction ID      Item  Quantity Price Per Unit Total Spent  \
1       TXN_4977031      Cake       4.0            3.0        12.0   
10      TXN_2548360     Salad       5.0            5.0        25.0   
19      TXN_3709394     Juice       4.0            3.0        12.0   
21      TXN_3567645  Smoothie       4.0            4.0        16.0   
24      TXN_9400181  Sandwich       5.0            4.0        20.0   
...             ...       ...       ...            ...         ...   
9962    TXN_4723089  Sandwich       4.0            4.0        16.0   
9970    TXN_5762440  Sandwich       5.0            4.0        20.0   
9971    TXN_6120851     Salad       5.0            5.0        25.0   
9974    TXN_8076061       Tea       4.0            1.5         6.0   
9979    TXN_9933628  Smoothie       5.0            4.0        20.0   

     Payment Method  Location Transaction Date  
1              Cash  In-store       2023-05-16  
10             Cash  Takeaway       2023-11-07  
19             Cash  Takeaway       2023-01-15  
21      Credit Card  Takeaway       2023-03-30  
24             Cash  In-store       2023-06-03  
...             ...       ...              ...  
9962           Cash  In-store       2023-05-23  
9970           Cash  In-store       2023-03-05  
9971           Cash  Takeaway       2023-02-04  
9974           Cash  In-store       2023-04-01  
9979           Cash  In-store       2023-07-20  

[1266 rows x 8 columns]

In [47]:
df.sort_values(by='Total Spent', ascending=False)

Transaction ID    Item  Quantity Price Per Unit Total Spent  \
5198    TXN_8847610   Juice       3.0            3.0         9.0   
5764    TXN_9188172   Juice       3.0            3.0         9.0   
3136    TXN_2613440   Juice       3.0            3.0         9.0   
8314    TXN_8082317   Juice       3.0            3.0         9.0   
5737    TXN_5594695    Cake       3.0            3.0         9.0   
...             ...     ...       ...            ...         ...   
4000    TXN_1130142  Cookie       1.0            1.0         1.0   
7015    TXN_9206049  Cookie       1.0            1.0         1.0   
6160    TXN_6815801  Cookie       1.0            1.0         1.0   
2253    TXN_9833245  Cookie       1.0            1.0         1.0   
3261    TXN_9720549  Cookie       1.0            1.0         1.0   

      Payment Method  Location Transaction Date  
5198  Digital Wallet  Takeaway       2023-12-06  
5764  Digital Wallet  In-store       2023-08-27  
3136     Credit Card  In-store       2023-04-15  
8314            Cash  Takeaway       2023-08-18  
5737     Credit Card  In-store       2023-01-18  
...              ...       ...              ...  
4000     Credit Card  In-store       2023-03-13  
7015     Credit Card  In-store       2023-09-17  
6160  Digital Wallet  Takeaway       2023-03-15  
2253  Digital Wallet  Takeaway       2023-04-30  
3261     Credit Card  In-store       2023-07-30  

[3089 rows x 8 columns]

In [53]:
teste = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])

In [54]:
teste * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

In [55]:
np.sqrt(teste)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128])

In [57]:
teste[5:12]

array([ 6,  7,  8,  9, 10, 11, 12])

In [60]:
np.random.randint(1, 11, size=(3, 3))

array([[4, 3, 3],
       [2, 9, 6],
       [1, 8, 9]], dtype=int32)

In [61]:
np.mean(teste)

np.float64(7.0)

In [68]:
np.mean(df[df['Quantity'] > 3]['Quantity'])

np.float64(4.504739336492891)

In [69]:
np.std(df[df['Quantity'] > 3]['Quantity'])

np.float64(0.49997753818507407)

In [74]:
np.median(df[df['Quantity'] > 3]['Quantity'])

np.float64(5.0)

In [90]:
df['Location'].value_counts()

Location
Takeaway    1547
In-store    1542
Name: count, dtype: int64

In [91]:

location_counts_filtered = df[df['Quantity'] > 3]['Location'].value_counts()

print(location_counts_filtered)


Location
Takeaway    634
In-store    632
Name: count, dtype: int64
